### ISSUE TITLE
Incorrect shipping cost calculation

### ISSUE THREAD

**Issue by artmouse** [PerspectiveTeam/NovaposhtaShipping#1]
If the base currency differs from the default currency, the shipping cost is converted at the specified rate.

![image](https://github.com/PerspectiveTeam/NovaposhtaShipping/assets/527232/02e9b5d2-4f08-4d2a-8cfb-fa154e6963ef)

![image](https://github.com/PerspectiveTeam/NovaposhtaShipping/assets/527232/90dc880d-95a5-4c83-9464-22c67b2c7920)

**Comment by monteshot** [comment]
@artmouse 
Could you check this potential fix on your M2 instance ?

https://github.com/PerspectiveTeam/NovaposhtaShipping/pull/3
